name = "edge-performance-test"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[[env.production.vars]]
NODE_ENV = "production"
